env:
  bcNodeWsURI: ws://123.56.143.169:11011
  bcNodeRpcURI: http://123.56.143.169:11011
  bcWalletRpcURI: http://123.56.143.169:8095
  scanRpcAppPackage: com.tsc.service.base.rpcApp
  scanRpcWalletPackage: com.tsc.service.base.rpcWallet

  wsPort: 8887
  faucetPwd: 123456
  faucetRegAcct: faucet
  faucetRefAcct: faucet
  faucetRefPerct: 0

#========================================================================

#========================================================================
debug: true
logging:
  level: info
  path: /logs/
  pattern.:
    console: "%d{yyyy-MM-dd HH:mm:ss,SSS} [%class:%line] - %m%n"
#========================================================================
endpoints:
  enabled: false