#========================================================================

spring:
  datasource:
    url: jdbc:postgresql://pgsql.tangsheng.com:9999/db_tcis
    username: postgres
    password: 123456
    driverClassName: org.postgresql.Driver
  jpa:
    show-sql: true
    generate-ddl: false
#    database-platform : com.tsc.jsonb.dialect.JSONBPostgreSQLDialect
  aop:
    proxy-target-class: true
    auto: true
redis:
  port: 6379
  timeout: 6000
  host: redis.tangsheng.com

  pool:
    maxTotal: 5000
    #最大能够保持idel状态的对象数
    maxIdle: 5000
    #当池内没有返回对象时，最大等待时间
    maxWait: 3000
    #当调用borrow Object方法时，是否进行有效性检查
    testOnBorrow: true
    #当调用return Object方法时，是否进行有效性检查
    testOnReturn: true

#创蓝短息常量
phone:
  engine: true
  sms:
    serverurl: http://222.73.117.156/msg/index.jsp
    username: vip-td-tz
    password: Tdjr888888
  voice:
    username: vip-yuyin
    password: Tdjr888888
    serverurl: http://222.73.117.156/msg/index.jsp

#========================================================================
ghb:
  apiurldev: http://183.63.131.106:40015/extServiceTest/ghbExtService.do
  apiurlsit: http://183.63.131.106:40011/extService/ghbExtService.do
  apiurluat: http://183.63.131.106:40013/extService/ghbExtService.do
  channelCode: p2p001
  tsc3DesKey: 847CAC05A5CBAF2B
  tscPriKey: MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDeiSXIs+HyB4RJqP6Vdm3SoacAW/wz1OVXOqtifA8St+rEoBR2LFiKNnTaEWcWLpQ/pxFvK+6tXYoMzPd2QA37ufrU0mK1kHp/aq5oslKlpwEl9qvT8Jqhg4K+QwWb7BEYYGCAk3r4BM6QQyEGbnkEhxcvc/Ef7HtZxuLcpeOIZ951GYQYDXbNsHU1HXVBi2yhLQy8HQVAL6pxBUevTJvX972vbb9ss/XGvBvUmpaYfHn59v0YS99DT89vVhDiPgMHxHizZY9OSiE/F8m9si71axXNHHjv49/R9lqkPWjSXkdTqwsi1oAxoH4hSuvaPpnNqpQVCXpWUA/KShmTztXXAgMBAAECggEBAJo3fyjEiDt7PBDz/WHEzbzfa+VS2cdtrXWy4dyBTszR/tm4rWHM++lr/7jkXqgzG+dybG1gZM+tuWKkA/KTfAHcKO58w+W4rsiSEookScSMwnbjw6Sj3F8k65d0VcunmsAAqqO2KCCELwKVrgYCmPmITiARnN23PQ7kiUGjDlT5jDYYsyxr165YkCgYEA9Den3IMp0DVL/I0V/U+ZsMwaVB5f0aG6yZLj/qA6qdUFW1kMiK0Lj+lPA0tH0qdQwIJ4RH2QrHfwD8DjaRr4VEZN37WqtIOJigXNZAM9N/dUQr0mYDSfx6RaEhlYww5Fgn8zq2HxcwQ+X70y2E40Ze3/QkbLFVZjYTBrH3NY9zUCgYEA6UWzQNOEnZ67PTsyf4v1T7jhOow2rwEYlMU06JgMwzIkDBl899eWWwY3/QddUmwZukDrKA760QRm5lBxyd4IVq9H33tVgsuyrtIdQxRX9UfllSlcLtj1DC9sh4LXdvWZ4tbbloIhxlPT9OrlGNSWS6biJJmD/7KCxe79A+Bz3lsCgYEApm6ziDUfLtTTlyazYLF5xSIjo0Yb+OpmOG9Rz7p0oD8baniScSa1JXtTrKQGK4p5HukLe2mzScZnJOVIVd3adNyAv7+3uVOXTSfNJKaMdvKoSt9LIu9aIJ1iAMmjUzMLrfZwSRDzknXG6EoxN3Z8gSaj+g/y4PTBv39W0dUzQS0CgYB0goCWZ078XtSML634MJJUwDWWRYPmgrihTaIwbgkp0ThZ5r0ZGM+bJQ7/zRbaXO24rkYFmv3BOd6fOBytQ72Mdj2CrJo4Gr9jO8SrxVRtSPytNJw7Ndemv2UIhdxSKTc0KjZBBTwTT7k0wcGtVji/DlozB437P1C7xbMPpaKZswKBgHrwa7mDvdtdSsods2Pi6xe9fQQbhWc1qPZ/LUarb6RpEcQL5qA2JAakq0pCWPFAaiu7u2zskKCBH5BKHEnMGxVvYLjK8V7RMofwf0WEhJvh7YcgTTxAjSpbLe670Xw0SrEeyawg7VgrFeHp4MEZ4OgCeSpa77wkmDk1eV310KeY
  tscPubKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA3oklyLPh8geESaj+lXZt0qGnAFv8M9TlVzqrYnwPErfqxKAUdixYijZ02hFnFi6UP6cRbyvurV2KDMz3dkAN+7n61NJitZB6f2quaLJSpacBJfar0/CaoYOCvkMFm+wRGGBggJN6+ATOkEMhBm55BIcXL3PxH+x7Wcbi3KXjiGfedRmEGA12zbB1NR11QYtsoS0MvB0FQC+qcQVHr0yb1/e9r22/bLP1xrwb1JqWmHx5+fb9GEvfQ0/Pb1YQ4j4DB8R4s2WPTkohPxfJvbIu9WsVzRx47+Pf0fZapD1o0l5HU6sLItaAMaB+IUrr2j6ZzaqUFQl6VlAPykoZk87V1wIDAQAB
  ghbPubKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA3oklyLPh8geESaj+lXZt0qGnAFv8M9TlVzqrYnwPErfqxKAUdixYijZ02hFnFi6UP6cRbyvurV2KDMz3dkAN+7n61NJitZB6f2quaLJSpacBJfar0/CaoYOCvkMFm+wRGGBggJN6+ATOkEMhBm55BIcXL3PxH+x7Wcbi3KXjiGfedRmEGA12zbB1NR11QYtsoS0MvB0FQC+qcQVHr0yb1/e9r22/bLP1xrwb1JqWmHx5+fb9GEvfQ0/Pb1YQ4j4DB8R4s2WPTkohPxfJvbIu9WsVzRx47+Pf0fZapD1o0l5HU6sLItaAMaB+IUrr2j6ZzaqUFQl6VlAPykoZk87V1wIDAQAB

#========================================================================
server:
  context-path: /
#========================================================================
debug: true
logging:
  level: info
  path: /logs/
  pattern.:
    console: "%d{yyyy-MM-dd HH:mm:ss,SSS} [%class:%line] - %m%n"
#========================================================================
